export enum UserErrors {
    NO_USER_FOUND = "NO-USER-FOUND",
    WRONG_CREDENTIALS = "wrong-credentials",
    USERNAME_ALREADY_EXISTS = "USERNAME-ALREADY-EXISTS"
}

export enum ProductErrors{
    NO_PRODUCT_FOUND = "NO-PRODUCT-FOUND",
    NOT_ENOUGH_STOCK = "NOT-ENOUGH-STOCK",
    NOT_ENOUGH_MONEY = "NOT-ENOUGH-MONEY"
}